[project]
authors = ["Bryn Pickering <17178478+brynpickering@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "openmod-features"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.2.0.dev"

[tasks.update-schema]
cmd = "python schema/schema_generator.py"

[tasks.add-tool]
args = ["tool_name"]
cmd = "copier copy gh:open-energy-transition/openmod-features --vcs-ref try-copier tools/{{ tool_name }} -d shortname={{ tool_name }}"

[tasks.update-tool]
args = ["tool_name"]
cmd = "copier update tools/{{ tool_name }} --defaults"

[dependencies]
pre-commit = ">=4.2.0,<5"
ruff = ">=0.12.4,<0.13"
python = ">=3.13.5,<3.14"
pydantic = ">=2.11.7,<3"
click = ">=8.2.1,<9"
copier = ">=9.10.2,<10"
