# SPDX-FileCopyrightText: openmod-features contributors
#
# SPDX-License-Identifier: CC0-1.0

[project]
authors = ["Bryn Pickering <17178478+brynpickering@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "openmod-features"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.2.0.dev"

[tasks.update-schema]
cmd = "python schema/schema_generator.py"

[tasks.add-tool]
args = ["tool_name", {"arg" = "version", "default" = "stable"}]
cmd = """copier copy gh:open-energy-transition/openmod-features {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} tools/{{ tool_name }} -d shortname={{ tool_name }} -d list_type=tool"""

[tasks.update-tool]
args = ["tool_name", {"arg" = "version", "default" = "stable"}, {"arg" = "flag", "default" = "--defaults"}]
cmd = """copier update tools/{{ tool_name }} {{ flag }} {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} --answers-file .metadata.yml -d list_type='tool'"""

[tasks.update-tool-metadata]
args = ["tool_name"]
cmd = "copier update tools/{{ tool_name }} --vcs-ref=:current: --answers-file .metadata.yml"

[tasks.add-use-case]
args = ["use_case_name", {"arg" = "version", "default" = "stable"}]
cmd = """copier copy gh:open-energy-transition/openmod-features {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} 'use-cases/{{ use_case_name }}' -d shortname='{{ use_case_name }}' -d list_type='use-case'"""

[tasks.update-use-case]
args = ["use_case_name", {"arg" = "version", "default" = "stable"}, {"arg" = "flag", "default" = "--defaults"}]
cmd = """copier update use-cases/{{ use_case_name }} {{ flag }} {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} --answers-file .metadata.yml -d list_type='use-case'"""

[tasks.update-use-case-metadata]
args = ["use_case_name"]
cmd = "copier update use-cases/{{ use_case_name }} --vcs-ref=:current: --answers-file .metadata.yml"

[tasks.check-links]
args = [{"arg" = "tool_name", "default" = "**"}]
cmd = "lychee --no-progress tools/{{ tool_name }}/*"

[tasks.test]
cmd = "pytest tests -nauto"

[dependencies]
pre-commit = ">=4.2.0,<5"
ruff = ">=0.12.4,<0.13"
python = ">=3.13.5,<3.14"
pydantic = ">=2.11.7,<3"
click = ">=8.2.1,<9"
copier = ">=9.10.2,<10"
lychee = ">=0.20.1,<0.21"
pytest = ">=8.3.4,<9"
pyyaml = ">=6.0.2,<7"
pytest-xdist = ">=3.8.0,<4"
