# SPDX-FileCopyrightText: openmod-features contributors
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
authors = ["Bryn Pickering <17178478+brynpickering@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "openmod-features"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.2.0.dev"

[tasks.update-schema]
cmd = "python scripts/schema_generator.py"

[tasks.add-tool]
args = ["tool_name", {"arg" = "version", "default" = "stable"}]
cmd = """copier copy gh:open-energy-transition/openmod-features {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} tools/{{ tool_name }} -d shortname={{ tool_name }} -d list_type=tool"""

[tasks.update-tool]
args = ["tool_name", {"arg" = "version", "default" = "stable"}, {"arg" = "flag", "default" = "--defaults"}]
cmd = """copier update tools/{{ tool_name }} {{ flag }} {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} --answers-file .metadata.yml -d list_type='tool'"""

[tasks.update-tool-metadata]
args = ["tool_name"]
cmd = "copier update tools/{{ tool_name }} --vcs-ref=:current: --answers-file .metadata.yml"

[tasks.add-use-case]
args = ["use_case_name", {"arg" = "version", "default" = "stable"}]
cmd = """copier copy gh:open-energy-transition/openmod-features {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} 'use-cases/{{ use_case_name }}' -d shortname='{{ use_case_name }}' -d list_type='use-case'"""

[tasks.update-use-case]
args = ["use_case_name", {"arg" = "version", "default" = "stable"}, {"arg" = "flag", "default" = "--defaults"}]
cmd = """copier update use-cases/{{ use_case_name }} {{ flag }} {% if version != "stable" %}--vcs-ref {{ version }}{% endif %} --answers-file .metadata.yml -d list_type='use-case'"""

[tasks.update-use-case-metadata]
args = ["use_case_name"]
cmd = "copier update use-cases/{{ use_case_name }} --vcs-ref=:current: --answers-file .metadata.yml"

[tasks.check-links]
args = [{"arg" = "tool_name", "default" = "**"}]
cmd = "pixi run pre-commit run validate-yaml-links --file tools/{{ tool_name }}/*"

[tasks.test]
cmd = "pytest tests -nauto"

[dependencies]
pre-commit = ">=4.6.2,<5"
ruff = ">=0.16.8,<0.17"
python = ">=3.14.7,<3.15"
pydantic = ">=2.13.5,<3"
click = ">=8.5.0,<9"
copier = ">=9.18.2,<10"
lychee = ">=0.24.2,<0.25"
pytest = ">=9.1.1,<10"
pyyaml = ">=6.0.3,<7"
pytest-xdist = ">=3.8.0,<4"
jsonschema = ">=4.26.0,<5"
requests = ">=2.34.2,<3"

[feature.website.dependencies]
pnpm = ">=12.4.1,<13"
nodejs = ">=26.10.0,<26.11"

[feature.website.tasks]
deploy-cloudflare = { "cmd" = "pnpm deploy:cloudflare", "cwd" = "website" }

[environments]
website = { features = ["website"], no-default-feature = true }
