# SPDX-FileCopyrightText: tools/calliope/features.yaml CODEOWNERS
# SPDX-FileCopyrightText: openmod-features contributors
#
# SPDX-License-Identifier: CC-BY-4.0

# Changes here will be overwritten by Copier
# DO NOT MANUALLY MODIFY THIS FILE
_commit: 6fd6237
_src_path: gh:open-energy-transition/openmod-features
docs: https://calliope.readthedocs.io
maintainers: brynpickering
name: calliope
shortname: calliope
source: https://github.com/calliope-project/calliope
