# Changes here will be overwritten by Copier
# DO NOT MANUALLY MODIFY THIS FILE
_commit: '5387176'
_src_path: gh:open-energy-transition/openmod-features
docs: https://calliope.readthedocs.io
maintainers: brynpickering
name: calliope
shortname: calliope
source: https://github.com/calliope-project/calliope
