# SPDX-FileCopyrightText: tools/calliope/features.yaml CODEOWNERS
# SPDX-FileCopyrightText: openmod-features contributors
#
# SPDX-License-Identifier: CC-BY-4.0

# Changes here will be overwritten by Copier
# DO NOT MANUALLY MODIFY THIS FILE
_commit: e363e40
_src_path: gh:open-energy-transition/openmod-features
description: Calliope is a free and open-source tool that makes it easy to build energy
    system models at scales ranging from urban districts to entire continents.
docs: https://calliope.readthedocs.io
list_type: tool
maintainers: brynpickering
name: calliope
shortname: calliope
source: https://github.com/calliope-project/calliope
