# Changes here will be overwritten by Copier
# DO NOT MANUALLY MODIFY THIS FILE
_commit: c5fd715
_src_path: gh:open-energy-transition/openmod-features
docs: https://osemosys.readthedocs.io/en/latest/?badge=latest
maintainers: willu47
name: Open Source Energy Modelling System
shortname: osemosys
source: https://github.com/OSeMOSYS/OSeMOSYS_GNU_MathProg
