# SPDX-FileCopyrightText: openmod-tracker contributors
#
# SPDX-License-Identifier: CC0-1.0

name: Run tests.

on:
  pull_request: # or runs on merges into main
    branches:
      - "main"
    paths:
      - schema/**
      - template/**
      - tests/**
      - copier.yml
      - pixi.toml
      - ruff.toml
      - .github/workflows/run-tests.yml

jobs:
  run-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          # For PRs, we need to fetch the full history to commit back
          fetch-depth: 0
          # Use a token that can create PRs and push to branches
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.2

      - name: Run tests
        run: pixi run test -v
